# Copyright 2025 Dotanuki Labs
# SPDX-License-Identifier: MIT

name: "CD"

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write
  pages: write
  id-token: write

jobs:
  docs-deploy:
    runs-on: ubuntu-24.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout source
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Prepare documentation assets
        uses: dotanuki-labs/github-actions/foss/prepare-ghpages@main

      - name: Deploy assets to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5

  docker-build:
    runs-on: ${{ matrix.build-args.runner }}
    strategy:
      matrix:
        build-args:
          - platform: linux/amd64
            platform-suffix: amd64
            runner: ubuntu-24.04
          - platform: linux/arm64
            platform-suffix: arm64
            runner: ubuntu-24.04-arm

    steps:
      - name: Project Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Docker metadata
        id: docker-metadata
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Set up docker-buildx
        uses: docker/setup-buildx-action@18ce135bb5112fa8ce4ed6c17ab05699d7f3a5e0 # v3.11.0

      - name: Log in to Github Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container Image
        id: build
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          push: true
          provenance: false
          platforms: ${{ matrix.build-args.platform }}
          labels: ${{ steps.docker-metadata.outputs.labels }}
          annotations: ${{ steps.docker-metadata.outputs.annotations }}
          outputs: type=registry,push=true
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}-${{ matrix.build-args.platform-suffix }}

  docker-manifest:
    runs-on: ubuntu-24.04
    needs: docker-build

    steps:
      - name: Project Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Log in to Github Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Docker manifest
        run: |
          docker manifest create "$latest" --amend "$package"-amd64 --amend "$package"-arm64
          docker manifest annotate --arch amd64 --os linux "$latest" "$package"-amd64
          docker manifest annotate --arch arm64 --os linux "$latest" "$package"-arm64
          docker manifest inspect "$latest"
          docker manifest push "$latest"
        env:
          package: ghcr.io/${{ github.repository }}:${{ github.sha }}
          latest: ghcr.io/${{ github.repository }}:latest
